name: 'Build Proto Action'
description: 'Setup and build protobuf files. Uses buf and protoc with gen dependencies.'
author: 'Nick Aguilar'
inputs:
  working-directory:
    description: 'The directory to run the build in.'
    required: false
    default: '.'
  buf-version:
    description: 'Version of buf to use.'
    required: false
    default: '1.10.0'
  protoc-version:
    description: 'Version of protoc to use.'
    required: false
    default: '21.12'
  plugins:
    description: 'List of plugins to use by protoc, separated by commas.'
    required: false
    default: 'go,go-grpc'
  push:
    required: false
    description: 'If the result should be pushed to the repo.'
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'
